### ISSUE TITLE
Allowing /tmp for git difftool

### ISSUE THREAD

**Issue by mvainola** [flathub/org.gnome.meld#11]
I set up Meld as my git difftool like this:

    [diff]
        tool = meld
    [difftool]
        prompt = false
    [difftool "meld"]
        cmd = flatpak run org.gnome.meld "$LOCAL" "$REMOTE"

When trying to display a diff, Meld is unable to open the temporary files created by git. This can be worked around by using `flatpak run --filesystem=/tmp`, but I wanted to know if Flathub would allow adding this permission to the manifest.

**Comment by bochecha** [comment]
Here's how I've set Meld as my difftool:

```ini
[diff]
tool = meld_flatpak
[difftool]
prompt = false
[difftool "meld_flatpak"]
cmd = flatpak run --file-forwarding org.gnome.meld \"@@\" $LOCAL \"@@\" \"@@\" $REMOTE \"@@\"
```

This works fine, without needing to allow `/tmp`.

Can you try whether it works for you?

**Comment by mvainola** [comment]
Thanks! I didn't know about `--file-forwarding` but it works just as well. I'll close this issue since allowing only the necessary files is much better than all of `/tmp`.

**Comment by dpward** [comment]
Unfortunately, `--file-forwarding` does not work for `git difftool --dir-diff`:

```
error: Invalid fd passed
/usr/libexec/git-core/git-difftool line 483: No such file or directory
```
