### ISSUE TITLE
Wrong license.  GPLv2 is  not proprietary

### ISSUE THREAD

**Issue by BrunoVernay** [flathub/org.gnome.meld#28]
On Flathub, the license is displayed as " Prorietary"  in red.
It is seems to be GPLv2 : https://gitlab.gnome.org/GNOME/meld

**Comment by bilelmoussaoui** [comment]
where do you see that?

**Comment by BrunoVernay** [comment]
On Software on Fedora 34 Gnome v40
![image](https://user-images.githubusercontent.com/132261/117193490-35662480-ade3-11eb-9461-40ff337e969d.png)

**Comment by hfiguiere** [comment]
When you see the source, it's not even coming from flathub.

Here it says the proper one:
https://flathub.org/apps/details/org.gnome.meld

**Comment by BrunoVernay** [comment]
OK wrong target, sorry.  I posted on Fedora forum related to the registry ... hope they fix their stuff.
